@startuml packages_model_name
set namespaceSeparator none
package "model_name" as model_name {
}
package "model_name.__main__" as model_name.__main__ {
}
package "model_name.core" as model_name.core {
}
package "model_name.core.metrics" as model_name.core.metrics {
}
package "model_name.core.models" as model_name.core.models {
}
package "model_name.core.schemas" as model_name.core.schemas {
}
package "model_name.io" as model_name.io {
}
package "model_name.io.configs" as model_name.io.configs {
}
package "model_name.io.datasets" as model_name.io.datasets {
}
package "model_name.io.osvariables" as model_name.io.osvariables {
}
package "model_name.io.registries" as model_name.io.registries {
}
package "model_name.io.services" as model_name.io.services {
}
package "model_name.jobs" as model_name.jobs {
}
package "model_name.jobs.base" as model_name.jobs.base {
}
package "model_name.jobs.evaluations" as model_name.jobs.evaluations {
}
package "model_name.jobs.explanations" as model_name.jobs.explanations {
}
package "model_name.jobs.inference" as model_name.jobs.inference {
}
package "model_name.jobs.kafkainference" as model_name.jobs.kafkainference {
}
package "model_name.jobs.promotion" as model_name.jobs.promotion {
}
package "model_name.jobs.training" as model_name.jobs.training {
}
package "model_name.jobs.tuning" as model_name.jobs.tuning {
}
package "model_name.scripts" as model_name.scripts {
}
package "model_name.settings" as model_name.settings {
}
package "model_name.utils" as model_name.utils {
}
package "model_name.utils.searchers" as model_name.utils.searchers {
}
package "model_name.utils.signers" as model_name.utils.signers {
}
package "model_name.utils.splitters" as model_name.utils.splitters {
}
model_name.__main__ --> model_name
model_name.__main__ --> model_name.scripts
model_name.core.metrics --> model_name.core
model_name.core.metrics --> model_name.core.models
model_name.core.metrics --> model_name.core.schemas
model_name.core.models --> model_name.core
model_name.core.models --> model_name.core.schemas
model_name.io.registries --> model_name.core
model_name.io.registries --> model_name.core.models
model_name.io.registries --> model_name.core.schemas
model_name.io.registries --> model_name.utils
model_name.io.registries --> model_name.utils.signers
model_name.io.services --> model_name.io.osvariables
model_name.jobs --> model_name.jobs.evaluations
model_name.jobs --> model_name.jobs.explanations
model_name.jobs --> model_name.jobs.inference
model_name.jobs --> model_name.jobs.promotion
model_name.jobs --> model_name.jobs.training
model_name.jobs --> model_name.jobs.tuning
model_name.jobs.base --> model_name.io
model_name.jobs.base --> model_name.io.services
model_name.jobs.evaluations --> model_name.core
model_name.jobs.evaluations --> model_name.core.metrics
model_name.jobs.evaluations --> model_name.core.schemas
model_name.jobs.evaluations --> model_name.io
model_name.jobs.evaluations --> model_name.io.datasets
model_name.jobs.evaluations --> model_name.io.registries
model_name.jobs.evaluations --> model_name.io.services
model_name.jobs.evaluations --> model_name.jobs
model_name.jobs.evaluations --> model_name.jobs.base
model_name.jobs.explanations --> model_name.core
model_name.jobs.explanations --> model_name.core.schemas
model_name.jobs.explanations --> model_name.io
model_name.jobs.explanations --> model_name.io.datasets
model_name.jobs.explanations --> model_name.io.registries
model_name.jobs.explanations --> model_name.jobs
model_name.jobs.explanations --> model_name.jobs.base
model_name.jobs.inference --> model_name.core
model_name.jobs.inference --> model_name.core.schemas
model_name.jobs.inference --> model_name.io
model_name.jobs.inference --> model_name.io.datasets
model_name.jobs.inference --> model_name.io.registries
model_name.jobs.inference --> model_name.jobs
model_name.jobs.inference --> model_name.jobs.base
model_name.jobs.promotion --> model_name.jobs
model_name.jobs.promotion --> model_name.jobs.base
model_name.jobs.training --> model_name.core
model_name.jobs.training --> model_name.core.metrics
model_name.jobs.training --> model_name.core.models
model_name.jobs.training --> model_name.core.schemas
model_name.jobs.training --> model_name.io
model_name.jobs.training --> model_name.io.datasets
model_name.jobs.training --> model_name.io.registries
model_name.jobs.training --> model_name.io.services
model_name.jobs.training --> model_name.jobs
model_name.jobs.training --> model_name.jobs.base
model_name.jobs.training --> model_name.utils
model_name.jobs.training --> model_name.utils.signers
model_name.jobs.training --> model_name.utils.splitters
model_name.jobs.tuning --> model_name.core
model_name.jobs.tuning --> model_name.core.metrics
model_name.jobs.tuning --> model_name.core.models
model_name.jobs.tuning --> model_name.core.schemas
model_name.jobs.tuning --> model_name.io
model_name.jobs.tuning --> model_name.io.datasets
model_name.jobs.tuning --> model_name.io.services
model_name.jobs.tuning --> model_name.jobs
model_name.jobs.tuning --> model_name.jobs.base
model_name.jobs.tuning --> model_name.utils
model_name.jobs.tuning --> model_name.utils.searchers
model_name.jobs.tuning --> model_name.utils.splitters
model_name.scripts --> model_name
model_name.scripts --> model_name.io
model_name.scripts --> model_name.io.configs
model_name.scripts --> model_name.settings
model_name.settings --> model_name
model_name.settings --> model_name.jobs
model_name.utils.searchers --> model_name.core
model_name.utils.searchers --> model_name.core.metrics
model_name.utils.searchers --> model_name.core.models
model_name.utils.searchers --> model_name.core.schemas
model_name.utils.searchers --> model_name.utils
model_name.utils.searchers --> model_name.utils.splitters
model_name.utils.signers --> model_name.core
model_name.utils.signers --> model_name.core.schemas
model_name.utils.splitters --> model_name.core
model_name.utils.splitters --> model_name.core.schemas
@enduml
