name: Setup
description: Setup for project workflows
runs:
  using: composite
  steps:
    - run: pipx install invoke poetry
      shell: bash
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: poetry
