name: Setup
description: Setup workflows.
runs:
  using: composite
  steps:
    - run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: poetry
