# name: Commons
# description: Perform common actions before all workflows.
# inputs:
#   poetry-version:
#     default: "1.6.1"
#     description: "Poetry Version"
#   python-version:
#     default: "3.10"
#     description: "Python Version"
# permissions:
#   id-token: write
# runs:
#   using: composite
#   steps:
#     - name: Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: ${{ inputs.python-version }}
#     - name: Poetry
#       uses: snok/install-poetry@v1
#       with:
#         version: ${{ inputs.poetry-version }}
