name: Main
on:
  push:
    branches:
      - main
      - '*'
concurrency:
  group: main
  cancel-in-progress: true
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'poetry'
      - run: poetry install
      - run: poetry run inv docs
      - run: poetry run inv checks
      - run: poetry run inv containers
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/
          branch: gh-pages
      - run: docker push ghcr.io/fmind/bikes:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
