name: Main
on:
  push:
    branches:
      - main
      - '*'
concurrency:
  group: main
  cancel-in-progress: true
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'poetry'
      - run: poetry install
      - run: poetry run inv packages
      - run: poetry run inv checks
      - run: poetry run inv docs
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/build/
      - uses: docker/build-push-action@v3
        with:
          push: true
          registry: ghcr.io
          tags: fmind/bikes:latest
          file: ./docker/Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
